### ISSUE TITLE
No Documentation regarding how to contribute

### ISSUE THREAD

**Issue by codeglock** [codeglocks/flutter-awesome-ui#6]
There were no official documentation regarding how public users contribute to this project,
It is nice to have some official guide as soon as possible
thank you!

**Comment by Dasunx** [comment]
We are currently working on the documentation about how contributions should done and how to get most out of this project,
we will update the documentation as soon as possible.
This issue will remain as open since then.
Thank you @codeglock

**Comment by dasunx** [comment]
We are currently working on the documentation about how contributions should be done and how to get the most out of this project,
we will update the documentation as soon as possible.
This issue will remain as open till then.
Thank you @codeglock

**Comment by dasunx** [comment]
we added contributing guidelines.
#11 with this pull request.
